# Generated by Django 5.2.5 on 2025-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("con", models.TextField()),
                ("ref", models.JSONField(default=list)),
                ("time", models.CharField(blank=True, max_length=100)),
                ("field", models.CharField(blank=True, max_length=100)),
                ("theme", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("tag", models.CharField(blank=True, max_length=50)),
                ("doc", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
