# Generated by Django 5.2.5 on 2025-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransHistory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historynode",
            old_name="doc",
            new_name="oridoc",
        ),
        migrations.AddField(
            model_name="historynode",
            name="mkdoc",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
