# Generated by Django 5.2.5 on 2025-09-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransHistory", "0003_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
