# Generated by Django 5.2.5 on 2025-09-30 16:00

import TransHistory.models
import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TransHistory", "0004_contributor_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="historynode",
            name="details",
            field=martor.models.MartorField(
                blank=True,
                help_text="Write a new page in Markdown",
                max_length=3000,
                null=True,
                validators=[TransHistory.models.validate_markdown_length],
                verbose_name="History Details",
            ),
        ),
    ]
