# Generated by Django 5.2.5 on 2025-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransHistory", "0005_historynode_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="historynode",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
