# Generated by Django 5.2.5 on 2025-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransHistory", "0006_historynode_cover"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historynode",
            old_name="time",
            new_name="time_name",
        ),
        migrations.AlterField(
            model_name="historynode",
            name="ref",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
