# Generated by Django 5.2.5 on 2025-10-03 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransHistory", "0007_rename_time_historynode_time_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historynode",
            name="time",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-9999),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
    ]
